import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import { mkdirSync, readFileSync, symlinkSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { test } from 'node:test';
import { tempDir, workflowRunBlock } from './lint-kit.mjs';

// Execute the shipped classifier, including its Git operations, against local
// commits. The fake generator writes the same paths as pinned tend's init.
const workflow = readFileSync(new URL('../.github/workflows/workflow-audit.yaml', import.meta.url), 'utf8');
const auditBlock = workflowRunBlock(workflow, 'Audit workflow file changes');
const classifier = auditBlock.slice(auditBlock.indexOf('is_tend_regen() {'), auditBlock.indexOf('\nREPORT=$(mktemp)'));
const original = '# Generated by tend 0.1.24. Regenerate with: uvx tend@latest init\noriginal\n';
const generated = original.replace('original', 'generated');

test('run-block extraction never borrows an unnamed following step', () => {
  for (const firstField of ['id: unrelated', 'if: success()']) {
    const source = `      - name: Target
        uses: vendor/action@v1
      - ${firstField}
        run: |
          echo wrong-step
`;
    assert.throws(() => workflowRunBlock(source, 'Target'), /missing run block/);
  }
});

function fixture(t) {
  const dir = tempDir(t, 'workflow-audit-');
  const repo = join(dir, 'repo');
  const bin = join(dir, 'bin');
  mkdirSync(repo);
  mkdirSync(bin);
  const env = { ...process.env, PATH: `${bin}:${process.env.PATH}`, GIT_CONFIG_NOSYSTEM: '1' };
  const git = (...args) => execFileSync('git', args, { cwd: repo, env, stdio: ['ignore', 'pipe', 'pipe'] }).toString().trim();
  git('init', '-q');
  git('config', 'user.email', 'test@example.invalid');
  git('config', 'user.name', 'Test');
  git('config', 'commit.gpgsign', 'false');
  const write = (path, value) => {
    const target = join(repo, path);
    mkdirSync(join(target, '..'), { recursive: true });
    writeFileSync(target, value);
  };
  const commit = () => { git('add', '-A'); git('commit', '-qm', 'fixture'); return git('rev-parse', 'HEAD'); };
  write('.config/tend.yaml', 'bot_name: test\n');
  write('.github/workflows/tend-review.yaml', original);
  commit();
  writeFileSync(join(bin, 'uvx'), `#!/bin/bash
set -euo pipefail
[[ "$1" = --no-config && "$2" = --no-env-file && "$3" = tend@0.1.24 && "$4" = init ]]
printf '%s' '${generated}' > .github/workflows/tend-review.yaml
printf 'generated actionlint' > .github/actionlint.yaml
if [[ -n "\${EXTRA_WORKFLOW:-}" ]]; then printf 'unexpected' > .github/workflows/tend-extra.yaml; fi
`, { mode: 0o755 });
  const classify = (sha, extraEnv = {}) => spawnSync('bash', ['-c', `set -euo pipefail
WINDOW_NON_WORKFLOW=(.config/tend.yaml .github/audit/ .vscode/)
${classifier}
is_tend_regen "$1"
`, 'classifier', sha], { cwd: repo, env: { ...env, ...extraEnv }, encoding: 'utf8' });
  return { dir, repo, write, commit, classify };
}

test('accepts exact regeneration and reports changed output', t => {
  const f = fixture(t);
  f.write('.github/workflows/tend-review.yaml', generated);
  const sha = f.commit();
  const result = f.classify(sha);
  assert.equal(result.status, 0, result.stderr);
  assert.equal(f.classify(sha, { EXTRA_WORKFLOW: '1' }).status, 1);
});

test('never materializes an unrelated symlink the generator would write through', t => {
  const f = fixture(t);
  const outside = join(f.dir, 'outside');
  writeFileSync(outside, 'untouched');
  symlinkSync(outside, join(f.repo, '.github/actionlint.yaml'));
  f.write('.github/workflows/tend-review.yaml', generated);
  assert.equal(f.classify(f.commit()).status, 0);
  assert.equal(readFileSync(outside, 'utf8'), 'untouched');
});

test('rejects symlink workflow inputs before running the generator', t => {
  const f = fixture(t);
  const outside = join(f.dir, 'outside');
  writeFileSync(outside, 'untouched');
  symlinkSync(outside, join(f.repo, '.github/workflows/tend-extra.yaml'));
  f.write('.github/workflows/tend-review.yaml', generated);
  assert.equal(f.classify(f.commit()).status, 1);
  assert.equal(readFileSync(outside, 'utf8'), 'untouched');
});

test('does not let gitignore conceal unexpected generated workflows', t => {
  const f = fixture(t);
  f.write('.gitignore', '.github/workflows/tend-extra.yaml\n');
  f.write('.github/workflows/tend-review.yaml', generated);
  assert.equal(f.classify(f.commit(), { EXTRA_WORKFLOW: '1' }).status, 1);
});

test('reports a config change even when its workflows reproduce', t => {
  const f = fixture(t);
  f.write('.config/tend.yaml', 'bot_name: changed\n');
  f.write('.github/workflows/tend-review.yaml', generated);
  assert.equal(f.classify(f.commit()).status, 1);
});
